config/routes.rb
DojoRubyBlog::Application.routes.draw do
  resources :posts do
    resources :comentarios
  end
  root :to => "posts#index"
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :post
  attr_accessible :autor, :conteudo
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :conteudo, :titulo
  has_many :comentarios
  validates :conteudo, :presence => true
  validates :titulo, :presence => true, :length => { :minimum => 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 
  private
 
  def autenticacao
    authenticate_or_request_with_http_basic do |usuario, senha|
      usuario == 'admin' && senha == '123'
    end
  end
 
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_filter :autenticacao, :only => [:destroy]
  
   def create
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.create(params[:comentario])
    redirect_to post_path(@post)
   end
   def destroy
    @post = Post.find(params[:post_id])
    @comentario = @post.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_filter :autenticacao, :except => [:index, :show] # linha adicionada
 
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Listing comentarios</h1>

<table>
  <tr>
    <th>Autor</th>
    <th>Conteudo</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.autor %></td>
    <td><%= comentario.conteudo %></td>
    <td><%= comentario.post %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Autor:</b>
  <%= @comentario.autor %>
</p>

<p>
  <b>Conteudo:</b>
  <%= @comentario.conteudo %>
</p>

<p>
  <b>Post:</b>
  <%= @comentario.post %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>11 CHOUSHINSEI</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">

<div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="#">Postagens</a></li>
          <li><a href="#">História</a></li>
          <li><a href="#">Contato</a></li>
        </ul>
        <h3 class="muted">Supernovas</h3>
      </div>

      <hr>

      <div class="jumbotron">
        <h1>CHOUSHINSEI</h1>
        <p class="lead"></p>
      </div>

<%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<hr />

<% @posts.each do |post| %>
<h2><%= link_to post.titulo, post %></h2>
<p><%= post.conteudo %></p>

<hr />
<% end%>

<%= link_to 'Nova postagem', new_post_path %>

app/views/posts/new.html.erb
<h1>Nova postagem</h1>

<%= render 'form' %>

<button class="btn btn-important"><%= link_to 'Voltar', posts_path %></button>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @post.titulo %></h2>
<p><%= @post.conteudo %></p>
 
<button class="btn btn-important"><%= link_to 'Editar Post', edit_post_path(@post) %></button>
<button class="btn btn-important"><%= link_to 'Nova postagem', new_post_path %></button>
<button class="btn btn-important"><%= link_to 'Voltar aos Posts', posts_path %></button>

<h3>Comentarios</h3>
<% @post.comentarios.each do |comentario| %>
  <p>
    <b>Autor:</b>
    <%= comentario.autor %>
  </p>
 
  <p>
    <b>Comentario:</b>
    <%= comentario.conteudo %>
  </p>
<p>
  <%= link_to 'Apagar Comentario', [comentario.post, comentario],
               :confirm => 'Tem certeza?',
               :method => :delete %>
</p
<hr />
<% end %>
 
<h3>Adicione um comentario:</h3>
<%= form_for([@post, @post.comentarios.build]) do |f| %>
  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 
<br />